### PR TITLE
msm8916: move kipper adreno firmware to qcom repo

### PR DESCRIPTION
**Pull request by jumoog**

### CODE REVIEW

**Comment by jumoog** [comment]
@mikeNG

**Comment by luca020400** [comment]
Add Adreno 300 firmware ( check asus_msm8916-common )

**Comment by jumoog** [comment]
https://github.com/TheMuppets/proprietary_vendor_asus/pull/163

**Comment by jumoog** [comment]
@luca020400 done!

**Comment by mikeNG** [comment]
Can you squash these into one change?

**Comment by mikeNG** [comment]
Please update https://github.com/LineageOS/android_device_qcom_common/blob/cm-14.1/extractors/graphics-msm8916-32.txt and regenerate the makefile using https://github.com/LineageOS/android_device_qcom_common/blob/cm-14.1/extractors/setup-makefiles.sh

**Pull request closed without merging**
