### PR TITLE
msm8996: graphics: Update graphics blobs

### PR DESCRIPTION
**Pull request by C457**
* Taken from ZTE Axon7 NRD90M B15 (LA.UM.5.5.r1-02200-8x96.0)

### CODE REVIEW

**Comment by Rashed97** [comment]
NRD90M is 7.0 while LA.UM.5.5.r1-02200-8x96.0 is 7.1.1. That's definitely not the
tag that ZTE used.

**Comment by C457** [comment]
Quote from ZTE R&D
"song.shenyang@zte
Attachments6:30 PM (3 hours ago)
to me 

This is the caf tag we are now using: LA.UM.5.5.r1-02200-8x96.0"

**Comment by Rashed97** [comment]
IDK what to tell you, is it 7.0 or 7.1?

**Comment by C457** [comment]
It's 7.0, but this is the same tag used in 7.0 kernel source. I  guess they backported it I have no idea but the kernel for official 7.0 is based on this exact tag as well.

**Comment by Rashed97** [comment]
I'll take a look at them when I'm at a computer then.

**Comment by xingrz** [comment]
AFAIK Nougat for Axon 7 haven't public beta yet. How did you get the ROM?

**Comment by C457** [comment]
I work directly with ZTE R&D. They are taking on a different approach for this device where they provide code, blobs, and necessary documentation.

**Comment by moetayuko** [comment]
Your blobs were built on 11/22/16, while LA.UM.5.5.r1-02200-8x96.0 was tagged on 2016-12-16 22:59:35

I don't think it makes sense

**Comment by C457** [comment]
Your right...but are they indeed newer?

**Comment by C457** [comment]
Unsure, but based on the build date I'm assuming they are.

**Pull request closed without merging**
